name: deepwalk-attest

on:
  workflow_dispatch:
  push:
    tags:
        - '*'

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            fulcio.sigstore.dev:443
            github.com:443
            rekor.sigstore.dev:443
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
            go-version-file: '.go-version'
      - name: go mod tidy
        run: make tidy
      - name: Build artifact
        run: make build
      - name: Attest
        uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e
        with:
          subject-path: '${{ github.workspace }}/deepwalk'
