name: deepwalk CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version-file: '.go-version'
      - name: go mod tidy
        run:
          make tidy
      - name: Run tests
        run:
          make test
      - name: Run benchmarks
        run:
          make bench
